### ISSUE TITLE
slacker test result message is printed twice

### ISSUE THREAD

**Issue by erickangMSFT** [vassilvk/slacker#21]
command to run:  slacker -fd ./spec/*.rb
version 1.0.17 (the same issue occurred on 1.0.15 as well)

Expected: the test result message contains one set of test result message.
Actual: the test result messages are duplicated.

```
* test result for:  website/searchForSuppliers.rb
WideWorldImportersTest (mssql)

WideWorldImporters: Website.SearchForSuppliers
F  successfully found suppliers (FAILED - 1)
.  failed with invalid supplier information


Failures:

  1) WideWorldImporters: Website.SearchForSuppliers successfully find suppliers
     Failure/Error: raise ("unittest failure demonstration")

     RuntimeError:
       unittest failure demonstration
     # ./spec/website/searchForSuppliers.rb:4:in `block (2 levels) in <top (required)>'

Failures:

  1) WideWorldImporters: Website.SearchForSuppliers successfully find suppliers
     Failure/Error: raise ("unittest failure demonstration")

     RuntimeError:
       unittest failure demonstration
     # ./spec/website/searchForSuppliers.rb:4:in `block (2 levels) in <top (required)>'

Finished in 0.05554 seconds (files took 1.55 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/website/searchForSuppliers.rb:3 # WideWorldImporters: Website.SearchForSuppliers successfully found suppliers

Finished in 0.05554 seconds (files took 1.55 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/website/searchForSuppliers.rb:3 # WideWorldImporters: Website.SearchForSuppliers successfully found suppliers

```

**Comment by erickangMSFT** [comment]
fix: https://github.com/erickangMSFT/slacker/commit/8e6b55ee5697d5ac860d7d0ae0a4fa9fe870deaa

**Comment by vassilvk** [comment]
Closed by #23

**Comment by ornatwork** [comment]
I'm still getting the duplicate failure using the -fd format - slacker (1.0.19)

```
Failures:

  1) tf_Account_Parent_Category returns the correct parent code
     Failure/Error: "#{res[0][:min_account_number]}-#{res[0][:max_account_number]}".should > expectation[:expected_parent_code]

       expected: > "100-200"
            got:   "100-200"
     # ./spec/app/table_functions/chart_of_accounts/tf_account_parent_category.rb:22:in `block (3 levels) in <top (required)>'
     # ./spec/app/table_functions/chart_of_accounts/tf_account_parent_category.rb:18:in `block (2 levels) in <top (required)>'

Failures:

  1) tf_Account_Parent_Category returns the correct parent code
     Failure/Error: "#{res[0][:min_account_number]}-#{res[0][:max_account_number]}".should > expectation[:expected_parent_code]

       expected: > "100-200"
            got:   "100-200"
     # ./spec/app/table_functions/chart_of_accounts/tf_account_parent_category.rb:22:in `block (3 levels) in <top (required)>'
     # ./spec/app/table_functions/chart_of_accounts/tf_account_parent_category.rb:18:in `block (2 levels) in <top (required)>'

Finished in 1 minute 22.65 seconds (files took 2.03 seconds to load)
456 examples, 1 failure

Failed examples:

rspec ./spec/app/table_functions/chart_of_accounts/tf_account_parent_category.rb:17 # tf_Account_Parent_Category returns the correct parent code

Finished in 1 minute 22.65 seconds (files took 2.03 seconds to load)
456 examples, 1 failure

Failed examples:

rspec ./spec/app/table_functions/chart_of_accounts/tf_account_parent_category.rb:17 # tf_Account_Parent_Category returns the correct parent code
```

**Comment by vassilvk** [comment]
Try adding `console_enabled: false` at the end of your `database.yml` file.

**Comment by ornatwork** [comment]
Yes, that works, thanks
